services:
  - docker

before_script:
  - travis_retry composer install --no-interaction --no-progress --prefer-source

script:
  - composer lint
  - docker run --rm -v "$PWD:/code" humanmade/plugin-tester

cache:
  timeout: 1000
  directories:
    - vendor
