services:
  - docker

before_script:
  - composer install

script:
  - composer run-script lint
  - docker run --rm -v "$PWD:/code" humanmade/plugin-tester

cache:
  timeout: 1000
  directories:
    - vendor
