services:
  - docker

before_script:
  - travis_retry composer install --no-interaction --no-progress --prefer-source

script:
  - composer lint
  - composer test

cache:
  timeout: 1000
  directories:
    - vendor
